### ISSUE TITLE
Release automation

### ISSUE THREAD

**Issue by yarikoptic** [citeproc-py/citeproc-py#123]
Windows ppl (like @rly are waiting for it)

should we wait for #120 or cut it before?

you ( @brechtm ) or me or someone else?

interested to `auto` it? We use it in increasing number of projects, see e.g. https://github.com/dandi/dandi-cli/ with its https://github.com/dandi/dandi-cli/blob/master/CHANGELOG.md produced by `auto` from PR titles and labels.

**Comment by brechtm** [comment]
#120 is only relevant to development, so don't let this delay a release.

As always, I'm quite busy with other projects, so it would be great if you could make a release. Don't feel obliged, though!

**Comment by yarikoptic** [comment]
ok, 0.6.0 released. Not sure why tarball did have generated .rng before and then not -- added .rng explicitly in MANIFEST.in .
Tested via duecredit on windows -- seems to install and work.  So the question remains: would you mind if we automate releasing?  I hate doing it manually these days.

**Comment by brechtm** [comment]
Ah, I didn't know what `auto` was. Looks neat! It seems a bit over the top at first glance. But I agree that having to manually create releases is a pain and holding back releases. So, go for it, if you feel up to configuring it!

Seems I'll just have to remember to never commit to master directly, but use PRs instead. Can pushes to master be disabled?

**Comment by yarikoptic** [comment]
I believe so.  In the branches section of the Settings for the repo you can configure branches protection.  
https://stackoverflow.com/questions/46146491/prevent-pushing-to-master-on-github#:~:text=To%20find%20it%20go%20to,people%20who%20are%20not%20moderators.

@jwodder - isn't it a good idea for any repo using `auto` for releases?  or an overkill?

**Comment by jwodder** [comment]
@yarikoptic Any commits made directly to `master` are displayed by `auto` in their own section, [as seen here](https://github.com/dandi/dandi-cli/releases/tag/0.17.0).  Whether that's desirable or not is up to you.

Note that, if branch protection is enabled, `auto` will need to be supplied with a personal admin token in order to push CHANGELOG commits to `master`, [as described here](https://intuit.github.io/auto/docs/build-platforms/github-actions#running-with-branch-protection).

**Comment by tmorrell** [comment]
It would be great to get release automation implemented. @yarikoptic or @jwodder if you have experience with auto I'd be happy to review a pull request. Otherwise I've used https://github.com/pypa/gh-action-pypi-publish and can put together a PR

**Comment by tmorrell** [comment]
Is there any opposition to me creating a `test` branch and setting up release automation to test.pypi.org there? This is one of those processes that is hard to test in a fork.

I'd then do a pull request to master, where we'd have to set up the real connection https://docs.pypi.org/trusted-publishers/adding-a-publisher/

**Comment by yarikoptic** [comment]
sad we dropped a ball on this. @tmorrell -- no opposition but also given limited cycles we have I think the easiest is to just to plow forward and get this implemented... Meanwhile we need to cut a release since we have accumulated a bit

```shell
❯ git describe
v0.6.0-58-g7118938
```

and last release was years back!

```shell
❯ git show v0.6.0 | head -n 3
tag v0.6.0
Tagger: Yaroslav Halchenko <debian@onerussian.com>
Date:   Thu May 27 15:37:57 2021 -0400
```

I will try to find time in coming days for this.

After that, @jwodder would you be so kind to give an initial "implementation" on this?

**Comment by castedo** [comment]
Thanks @yarikoptic and @jwodder. Once a new release is out, i'm happy to be a 3rd party to quickly test pip installing it fresh in a few linux containers and run some of my unit tests that depend on citeproc-py.

**Comment by tmorrell** [comment]
@yarikoptic thanks for moving this forward. Do you have the pypi permissions to get the token?

I've created a PR for the changes changes. https://github.com/citeproc-py/citeproc-py/pull/154 Let me know what else would be helpful to move this forward.

**Comment by yarikoptic** [comment]
@castedo 0.7.0 is out on pypi.  Let's continue with automations via
- #154 , and 
- #153 

@tmorell , and attn @brechtm for "1 bus factor" aspect - apparently I cannot manage but can mint token and upload. So I have added the secret, and overall we are pretty much ready with #153 -- just need to convert everything to .md

**Comment by yarikoptic** [comment]
ok -- we were so close! ;)  but also wrong since we do have 0.7.0 release already for which I did not push tag (the curse of manual labor -- pushed now):

```
✔  success   Calculated SEMVER bump: patch
ℹ  info      Calculated next version to be: 0.6.1
ℹ  info      Old changelog exists, prepending changes.
ℹ  info      Wrote new changelog to filesystem.
[master d760592] Update CHANGELOG.md [skip ci]
 1 file changed, 52 insertions(+)
ℹ  info      Committed new changelog.
ℹ  info      Calling version hook
v0.6.0
ℹ  info      Tagging new tag: v0.6.0 => v0.6.1
ℹ  info      Calling after version hook
68b0c4e8f94ae0452ba15e028e1f4cd15738a786	refs/heads/master
ℹ  info      Branch: master
ℹ  info      HEADs: 68b0c4e8f94ae0452ba15e028e1f4cd15738a786	refs/heads/master
ℹ  info      Current branch is up to date, proceeding with release
ℹ  info      Calling publish hook
ℹ  info      Pushing new tag to GitHub
remote: Permission to citeproc-py/citeproc-py.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/citeproc-py/citeproc-py/': The requested URL returned error: 403
Error: Running command 'git' with args [push, --follow-tags, --set-upstream, https://github.com/citeproc-py/citeproc-py, master] failed

remote: Permission to citeproc-py/citeproc-py.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/citeproc-py/citeproc-py/': The requested URL returned error: 403

    at ChildProcess.<anonymous> (/snapshot/auto/packages/core/src/utils/exec-promise.ts:76:23)
    at ChildProcess.emit (node:events:527:28)
    at ChildProcess.emit (node:domain:475:12)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)Error
    at Object.execPromise (/snapshot/auto/packages/core/src/utils/exec-promise.ts:17:20)
    at /snapshot/auto/plugins/git-tag/dist/index.js:85:26
    at eval (eval at create (/snapshot/auto/node_modules/tapable/lib/HookCodeFactory.js:75:10), <anonymous>:16:17)
    at new Promise (<anonymous>)
    at Hook.eval [as promise] (eval at create (/snapshot/auto/node_modules/tapable/lib/HookCodeFactory.js:75:10), <anonymous>:6:8)
    at Hook.PROMISE_DELEGATE [as _promise] (/snapshot/auto/node_modules/tapable/lib/Hook.js:22:14)
    at Auto.publishFullRelease (/snapshot/auto/packages/core/src/auto.ts:1803:32)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Auto.shipit (/snapshot/auto/packages/core/src/auto.ts:1664:21)
Error: Process completed with exit code 1.
```

I thin is just a matter of us needing to provide GITHUB_TOKEN ... need to run ATM, will do/check later

**Comment by tmorrell** [comment]
I'm playing around a GitHub App to bypass branch protection https://github.blog/changelog/2022-05-17-consistently-allow-github-apps-as-exceptions-to-branch-protection-rules. Not sure if it's going to work though.

**Comment by yarikoptic** [comment]
we tried it "hot" (in principle -- can be tried on a "throw away" repo configured in the same way... but indeed who knows what "similarity" would differ)

<details>
<summary>did not work in a similar way</summary> 

```shell
To https://github.com/citeproc-py/citeproc-py
3106
 * [new tag]         v0.7.1 -> v0.7.1
3107
 ! [remote rejected] master -> master (push declined due to repository rule violations)
3108
error: failed to push some refs to 'https://github.com/citeproc-py/citeproc-py'
3109
Error: Running command 'git' with args [push, --follow-tags, --set-upstream, https://****FH97@github.com/citeproc-py/citeproc-py, master] failed
3110

3111
remote: error: GH013: Repository rule violations found for refs/heads/master.        
3112
remote: Review all repository rules at https://github.com/citeproc-py/citeproc-py/rules?ref=refs%2Fheads%2Fmaster        
3113
remote: 
3114
remote: - Changes must be made through a pull request.        
3115
remote: 
3116
remote: - 7 of 7 required status checks are expected.        
3117
remote: 
3118
To https://github.com/citeproc-py/citeproc-py
3119
 * [new tag]         v0.7.1 -> v0.7.1
3120
 ! [remote rejected] master -> master (push declined due to repository rule violations)
3121
error: failed to push some refs to 'https://github.com/citeproc-py/citeproc-py'
```
</details>

I have pushed again the deletion of the tag.  Sure thing we could switch to using ssh deploy key - just then change pushurl for the remote to use ssh... there is a dedicated setting allowing for deploy keys to bypass. anyone has free cycles?

**Comment by yarikoptic** [comment]
woohoo -- we are done!  I chased #158 with
- #159 
which released 0.8.1 .
